[package]
name = "tree-fs"
version = "0.2.1"
edition = "2021"
description = "Provides a convenient way to create a tree of files"
authors = ["Elad Kaplan <kaplan.elad@gmail.com>"]
documentation = "https://docs.rs/tree-fs/latest/tree_fs"
repository = "https://github.com/kaplanelad/tree-fs"
keywords = ["filesystem", "folders", "test", "assert"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
rand = { version = "0.8.5" }

[dev-dependencies]
