[package]
name = "temp-dir-builder"
version = "0.1.1"
edition = "2021"
description = "Provides a convenient way to create a temporary directory containing files"
authors = ["Elad Kaplan <kaplan.elad@gmail.com>", "Iohann Rabeson"]
keywords = ["filesystem", "folders", "test"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/IohannRabeson/temp-dir-builder"

[dependencies]
path-clean = "1.0.1"
rand = { version = "0.10.2" }
thiserror = "2.0.12"

[dev-dependencies]

[lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
